const DEFAULT_PORT = 3001;
const HEADING_TAGS = 'h1,h2,h3,h4,h5,h6';
const HTML5 = 'HTML 5';
const MILISEC_IN_SEC = 1000;
const REQUEST_TIMEOUT_IN_SEC = 60;

module.exports = {
  DEFAULT_PORT,
  HEADING_TAGS,
  HTML5,
  MILISEC_IN_SEC,
  REQUEST_TIMEOUT_IN_SEC
}